#!/usr/bin/env python3
"""
PowerFlow Demo - GitHub Connector Code Scanner

This script demonstrates PowerFlow's AI-powered code analysis feature using the
GitHub connector to search and analyze code from GitHub repositories, retrieve 
snippets, and report insights.

The GitHub connector uses API calls (search, search_branches) to access public
repositories without requiring user authentication tokens.
"""

import os
import sys
from pathlib import Path

# Add powerflow to path for demo purposes
sys.path.insert(0, str(Path(__file__).parent))

from powerflow import (
    Pipeline,
    GitHubConnectorScannerSource, 
    CodeSnippetProcessor, 
    Destination,
)


def main():
    """Run GitHub connector code scanning demo."""
    print("\n" + "🚀"*40)
    print(" "*15 + "PowerFlow GitHub Connector Demo")
    print(" "*10 + "AI-Powered Code Analysis and Reporting")
    print("🚀"*40)
    
    # Configuration
    GITHUB_ISSUE_COMMENT_URL = "https://api.github.com/repos/gc10a/flowmetrics-powerflow/issues/1/comments"
    GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")  # Optional: only for posting results
    GITHUB_REPO = "YOUR_USERNAME/YOUR_CONNECTED_REPOSITORY"  # Repository to scan
    
    try:
        # Create an AI-powered code analysis and reporting pipeline
        pipeline = Pipeline(name="AI Code Insight Reporter")
        
        # Stage 1: Use GitHub connector to search and scan repository code files
        print("Stage 1: Using GitHub connector to search repository...")
        pipeline.add_stage(
            GitHubConnectorScannerSource(
                repository=GITHUB_REPO,
                query="tokenizer OR database OR secret OR config",  # Search query
                include_patterns=["*.py", "*.js", "*.ts", "*.go", "*.java"],
                exclude_patterns=["*.md", "*.txt", "*.json", "test_*.py"],
                topn=50  # Number of results to retrieve
            )
        )
        
        # Stage 2: Get AI-powered code snippets
        print("Stage 2: Processing code snippets with AI...")
        pipeline.add_stage(
            CodeSnippetProcessor(
                min_lines=10,                     # Minimum lines for a snippet
                max_snippets_per_file=3,         # Maximum snippets to get per file
                focus_keywords=["schemas", "engine", "database", "app"], # Keywords to prioritize snippet extraction
            )
        )
        
        # Stage 3: Report insights to GitHub Issue
        print("Stage 3: Preparing to send insights to GitHub...")
        if GITHUB_TOKEN:
            # Use direct API call with token
            pipeline.add_stage(
                Destination(
                    url=GITHUB_ISSUE_COMMENT_URL,
                    method="POST",
                    headers={
                        "Authorization": f"token {GITHUB_TOKEN}",
                        "Content-Type": "application/json",
                        "Accept": "application/vnd.github.v3+json"
                    },
                    body_template='{"body": "## PowerFlow AI Code Insights Report\\n\\nHere are some automatically extracted code snippets for review:\\n\\n```json\\n$DATA\\n```\\n\\n---\\n*Generated by PowerFlow AI Reporter*"}'
                )
            )
        else:
            # Use Agent to post the comment manually using browser tool on the GitHub issue page
            print("  Using Agent to post comment (no token provided) on browser tool to post the comment manually")
            pipeline.add_stage(
                Destination(
                    url=GITHUB_ISSUE_COMMENT_URL,
                    method="AGENT",  # Agent to post manually using browser tool on the GitHub issue page
                    body_template='{"body": "## PowerFlow AI Code Insights Report\\n\\nHere are some automatically extracted code snippets for review:\\n\\n```json\\n$DATA\\n```\\n\\n---\\n*Generated by PowerFlow AI Reporter*"}'
                )
            )
        
        # Run the analysis and reporting pipeline!
        print("\n" + "-"*80)
        print("Running pipeline...")
        print("-"*80 + "\n")
        
        result = pipeline.run()
        
        print("\n" + "="*80)
        if result.success:
            print("✅ AI Code Insight analysis complete!")
            print("   Check the GitHub issue for details:")
            print(f"   https://github.com/{GITHUB_REPO.replace('YOUR_USERNAME/YOUR_CONNECTED_REPOSITORY', 'gc10a/flowmetrics-powerflow')}/issues/1")
            if not GITHUB_TOKEN:
                print("\n   💡 Note: Comment posted via Agent (no token required)")
        else:
            print("❌ Code insight analysis failed with errors:")
            for error in result.errors:
                print(f"   • {error}")
        print("="*80)
        
        print("\n📊 Pipeline Statistics:")
        print(f"  • Records processed: {result.metadata.get('record_count', 0)}")
        print(f"  • Duration: {result.metadata.get('duration', 0):.2f}s")
        
        print("\nNext steps:")
        print("  1. Change GITHUB_REPO to scan different repositories")
        print("  2. Modify the search query to find different code patterns")
        print("  3. Customize include_patterns to scan specific file types")
        print("  4. Adjust focus_keywords to target specific code patterns")
        print("  5. Check out examples/ directory for more use cases")
        print("  6. Read the README.md for full documentation\n")
        
    except Exception as e:
        print(f"\n❌ Error running demo: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
